# Generated by Django 5.2.3 on 2025-06-21 22:10

import core.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACE22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chi')),
                ('prot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prot')),
            ],
        ),
        migrations.CreateModel(
            name='ACE66Mexico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ace_66_mexico', models.CharField(blank=True, max_length=100, null=True, verbose_name='ACE 66 / México')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10, verbose_name='Capítulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=50, verbose_name='Tipo de Doc')),
                ('entidad_emite', models.CharField(max_length=100, verbose_name='Entidad que emite')),
                ('disp_legal', models.CharField(max_length=255, verbose_name='Disp. Legal')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciasArancelarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can', models.CharField(blank=True, max_length=50, null=True, verbose_name='CAN')),
                ('ace_36', models.CharField(blank=True, max_length=50, null=True, verbose_name='ACE 36')),
                ('ace_47', models.CharField(blank=True, max_length=50, null=True, verbose_name='ACE 47')),
                ('ven', models.CharField(blank=True, max_length=50, null=True, verbose_name='VEN')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10, verbose_name='Título de Sección')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('notas_complementarias_nandina', models.TextField(blank=True, null=True, verbose_name='Notas Complementarias NANDINA')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('credencial', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('role', models.CharField(blank=True, choices=[('gerente', 'Gerente'), ('despachante', 'Despachante de Aduanas')], max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Arancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código completo')),
                ('partida', models.CharField(blank=True, max_length=4, null=True, verbose_name='Partida')),
                ('subpartida', models.CharField(blank=True, max_length=4, null=True, verbose_name='Subpartida')),
                ('subpartida_nacional', models.CharField(blank=True, max_length=6, null=True, verbose_name='Subpartida Nacional')),
                ('desagregacion_nacional', models.CharField(blank=True, max_length=10, null=True, verbose_name='Desagregación Nacional')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de la Mercancía')),
                ('ga', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='GA %')),
                ('ice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ICE %')),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('despacho_frontera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Despacho en Frontera')),
                ('ace22', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ace22')),
                ('ace66_mexico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ace66mexico')),
                ('capituloaranc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capitulo', verbose_name='Capítulo')),
                ('documentos_adicionales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.documentosadicionales')),
                ('preferencias_arancelarias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.preferenciasarancelarias')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='core.seccion'),
        ),
    ]
