# Generated by Django 5.2.3 on 2025-06-21 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_arancel_arancel_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arancel',
            name='arancel_padre',
            field=models.ForeignKey(blank=True, limit_choices_to={'arancel_padre__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aranceles_hijos', to='core.arancel', verbose_name='Arancel padre'),
        ),
        migrations.AlterField(
            model_name='arancel',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código completo'),
        ),
    ]
