# Generated by Django 5.2.3 on 2025-06-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_arancel_arancel_padre_alter_arancel_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arancel',
            options={'ordering': ['codigo']},
        ),
    ]
